version: "3.8"

services:
  backend:
    build: ./backend
    ports: 
      - 5000:5000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  
volumes:
  gmah:
